// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TaskManager.Models;

public partial class Task
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public Guid UserId { get; set; }

    public DateTime? CreateAt { get; set; }

    public virtual ApplicationUser? User { get; set; }
}